export const INITIAL_FINISHED_STORIES: FinishedStory[] = [
  {
    id: 'cancion-acustico',
    title: '🎵 Acústico: Alma y Cuerda',
    serviceType: 'cancion',
    category: 'bodas',
    categoryLabel: 'Bodas 💍',
    categoryIcon: '💍',
    audioUrl: '/audio/samples/acustico.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?q=80&w=1200',
    duration: '02:30',
    protagonists: 'Valeria & Andrés',
    clientQuote: '"Nuestra historia de amor acústica. ¡Lloramos de emoción al escucharla!"',
    synopsis: 'Muestra musical acústica con guitarra española, chelo y voces de estudio.',
    soundtrackStyle: 'Acústico Romántico',
    emotionalTone: 'Cálido y Cercano',
    tags: ['Acústico', 'Bodas', 'Romántico'],
    viewsCount: 4210,
    likesCount: 680,
    lyricsSnippet: 'Escribieron una canción desde cero con las cartas que nos mandábamos a distancia...'
  },
  {
    id: 'cancion-baile-boda',
    title: '💃 Baile de Boda: Nuestro Momento',
    serviceType: 'cancion',
    category: 'bodas',
    categoryLabel: 'Bodas 💍',
    categoryIcon: '💍',
    audioUrl: '/audio/samples/baile_boda.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?q=80&w=1200',
    duration: '02:45',
    protagonists: 'Sofía & Mateo',
    clientQuote: '"El primer baile perfecto. Nunca olvidaremos cómo sonó nuestra canción."',
    synopsis: 'Composición majestuosa diseñada específicamente para abrir la pista de baile nupcial.',
    soundtrackStyle: 'Balada Orquestal',
    emotionalTone: 'Majestuoso y Emocionante',
    tags: ['Baile', 'Vals', 'Bodas'],
    viewsCount: 5120,
    likesCount: 920,
    lyricsSnippet: 'Y en el centro de la pista, el mundo se detuvo al compás de nuestro vals...'
  },
  {
    id: 'cancion-balada-pop-hombre',
    title: '🎤 Balada Pop (Hombre): Voz del Corazón',
    serviceType: 'cancion',
    category: 'recuerdos',
    categoryLabel: 'Recuerdos 💖',
    categoryIcon: '💖',
    audioUrl: '/audio/samples/balada_pop_hombre.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516280440502-86927d2c3755?q=80&w=1200',
    duration: '03:10',
    protagonists: 'Luis para Ana',
    clientQuote: '"Le escribí mis sentimientos y EternIA lo convirtió en el mejor regalo de aniversario."',
    synopsis: 'Una balada pop masculina moderna y llena de sentimiento, ideal para aniversarios.',
    soundtrackStyle: 'Pop Moderno',
    emotionalTone: 'Romántico y Profundo',
    tags: ['Pop', 'Aniversario', 'Amor'],
    viewsCount: 3410,
    likesCount: 410,
    lyricsSnippet: 'No hay distancia que apague esta luz que me diste al llegar...'
  },
  {
    id: 'cancion-balada-pop-mujer',
    title: '🎤 Balada Pop (Mujer): Sentimiento Profundo',
    serviceType: 'cancion',
    category: 'recuerdos',
    categoryLabel: 'Recuerdos 💖',
    categoryIcon: '💖',
    audioUrl: '/audio/samples/balada_pop_mujer.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1493225457124-a1a2a5f0a886?q=80&w=1200',
    duration: '02:55',
    protagonists: 'Para mis Padres',
    clientQuote: '"Se la regalé a mis papás en sus bodas de plata. Fue el alma de la fiesta."',
    synopsis: 'Voz femenina interpretando una balada pop emotiva sobre el paso del tiempo y el amor.',
    soundtrackStyle: 'Pop Balada Femenina',
    emotionalTone: 'Nostálgico y Dulce',
    tags: ['Pop', 'Familia', 'Recuerdos'],
    viewsCount: 2840,
    likesCount: 310,
    lyricsSnippet: 'El tiempo pasa pero el brillo de sus ojos sigue intacto...'
  },
  {
    id: 'cancion-balada-ranchera',
    title: '🎸 Balada Ranchera: Pasión Regional',
    serviceType: 'cancion',
    category: 'celebraciones',
    categoryLabel: 'Celebraciones 🎉',
    categoryIcon: '🎉',
    audioUrl: '/audio/samples/balada_ranchera.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=1200',
    duration: '03:20',
    protagonists: 'Don Arturo (60 Años)',
    clientQuote: '"El mariachi sonó con mi historia. Lloré como niño recordando a mi pueblo."',
    synopsis: 'El clásico sonido ranchero y mariachi acompañando una historia de vida y raíces.',
    soundtrackStyle: 'Ranchero Tradicional',
    emotionalTone: 'Apasionado y Tradicional',
    tags: ['Ranchera', 'Mariachi', 'Celebración'],
    viewsCount: 4520,
    likesCount: 880,
    lyricsSnippet: 'De Jalisco hasta aquí, la guitarra canta lo que el pecho calla...'
  },
  {
    id: 'cancion-banda',
    title: '🎺 Banda: Fiesta y Alegría',
    serviceType: 'cancion',
    category: 'celebraciones',
    categoryLabel: 'Celebraciones 🎉',
    categoryIcon: '🎉',
    audioUrl: '/audio/samples/banda.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1520110120835-c96534a4c984?q=80&w=1200',
    duration: '02:50',
    protagonists: 'Fiesta de Egresados',
    clientQuote: '"Pusimos a todos a bailar. La tuba sonaba durísimo contando nuestras locuras."',
    synopsis: 'Estilo sinaloense lleno de energía, tambora y metales para celebrar a lo grande.',
    soundtrackStyle: 'Banda Sinaloense',
    emotionalTone: 'Alegre y Festivo',
    tags: ['Banda', 'Fiesta', 'Regional'],
    viewsCount: 6100,
    likesCount: 1200,
    lyricsSnippet: '¡Y que suene la banda, que esta noche no se acaba mi gente!...'
  },
  {
    id: 'cancion-blues',
    title: '🎹 Blues: Melancolía del Alma',
    serviceType: 'cancion',
    category: 'homenajes',
    categoryLabel: 'Homenajes 🕊️',
    categoryIcon: '🕊️',
    audioUrl: '/audio/samples/blues.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1200',
    duration: '04:10',
    protagonists: 'En Memoria del Abuelo',
    clientQuote: '"Él amaba el blues. La guitarra desgarrada expresó todo lo que nos faltó decirle."',
    synopsis: 'Blues profundo con armónica y guitarras eléctricas lentas en memoria de un ser querido.',
    soundtrackStyle: 'Blues Clásico',
    emotionalTone: 'Melancólico y Desgarrador',
    tags: ['Blues', 'Homenaje', 'Alma'],
    viewsCount: 2100,
    likesCount: 420,
    lyricsSnippet: 'El viento sopla fuerte, pero tu luz siempre brillará en esta casa...'
  },
  {
    id: 'cancion-cumbia',
    title: '🥁 Cumbia: Ritmo Tropical',
    serviceType: 'cancion',
    category: 'celebraciones',
    categoryLabel: 'Celebraciones 🎉',
    categoryIcon: '🎉',
    audioUrl: '/audio/samples/cumbia.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1533174000255-16c0b7d4cf11?q=80&w=1200',
    duration: '03:05',
    protagonists: 'XV Años de Caro',
    clientQuote: '"Quería una cumbia moderna para mis 15. Terminamos bailando hasta la madrugada."',
    synopsis: 'Ritmo tropical, güiro y acordeón para una celebración inolvidable.',
    soundtrackStyle: 'Cumbia Tropical',
    emotionalTone: 'Bailable y Divertido',
    tags: ['Cumbia', 'Baile', 'Fiesta'],
    viewsCount: 5500,
    likesCount: 950,
    lyricsSnippet: 'Baila Carolina, que la noche es tuya y la cumbia suena pa ti...'
  },
  {
    id: 'cancion-cumpleanos',
    title: '🎂 Cumpleaños: Un Año Más',
    serviceType: 'cancion',
    category: 'celebraciones',
    categoryLabel: 'Celebraciones 🎉',
    categoryIcon: '🎉',
    audioUrl: '/audio/samples/cumpleanos.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1530103862676-de3c9de59f9e?q=80&w=1200',
    duration: '02:20',
    protagonists: 'Pequeño Leo',
    clientQuote: '"La cara de mi hijo al escuchar su nombre en su propia canción de cumpleaños no tiene precio."',
    synopsis: 'Un tema festivo, alegre y lleno de buenos deseos para celebrar un cumpleaños especial.',
    soundtrackStyle: 'Pop Festivo',
    emotionalTone: 'Alegre y Optimista',
    tags: ['Cumpleaños', 'Infantil', 'Felicidad'],
    viewsCount: 3800,
    likesCount: 510,
    lyricsSnippet: 'Que apagues las velas y pidas deseos que vuelen al cielo, pequeño Leo...'
  },
  {
    id: 'cancion-funeral',
    title: '🕊️ Funeral: Recuerdo Eterno',
    serviceType: 'cancion',
    category: 'homenajes',
    categoryLabel: 'Homenajes 🕊️',
    categoryIcon: '🕊️',
    audioUrl: '/audio/samples/funeral.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470246973918-29a93221c455?q=80&w=1200',
    duration: '03:45',
    protagonists: 'Despedida de Martín',
    clientQuote: '"Fue la forma más hermosa de soltarlo. La música sanó una pequeña parte de nuestro dolor."',
    synopsis: 'Pieza solemne, coral e instrumental, diseñada para abrazar el alma en momentos de duelo.',
    soundtrackStyle: 'Coral y Cuerdas Solemnes',
    emotionalTone: 'Paz y Trascendencia',
    tags: ['Funeral', 'Solemne', 'Paz'],
    viewsCount: 1900,
    likesCount: 400,
    lyricsSnippet: 'No es un adiós, es un hasta pronto en las estrellas...'
  },
  {
    id: 'cancion-heavy-metal',
    title: '🤘 Heavy Metal: Fuerza y Poder',
    serviceType: 'cancion',
    category: 'recuerdos',
    categoryLabel: 'Recuerdos 💖',
    categoryIcon: '💖',
    audioUrl: '/audio/samples/heavy_metal.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?q=80&w=1200',
    duration: '04:00',
    protagonists: 'Biker Brothers',
    clientQuote: '"¡Pura energía! Pusieron nuestras anécdotas en un himno de rock pesado increíble."',
    synopsis: 'Guitarras distorsionadas y batería potente narrando una hermandad invencible.',
    soundtrackStyle: 'Heavy Metal Clásico',
    emotionalTone: 'Épico y Poderoso',
    tags: ['Metal', 'Rock', 'Hermandad'],
    viewsCount: 4100,
    likesCount: 600,
    lyricsSnippet: '¡Acelerando en la ruta, hermanos de sangre y de asfalto!...'
  },
  {
    id: 'cancion-iglesia',
    title: '⛪ Iglesia: Canto Celestial',
    serviceType: 'cancion',
    category: 'bautizos',
    categoryLabel: 'Bautizos 🕊️',
    categoryIcon: '🕊️',
    audioUrl: '/audio/samples/iglesia.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1438032005730-c779502fac39?q=80&w=1200',
    duration: '02:50',
    protagonists: 'Bautizo de Ana',
    clientQuote: '"El coro en latín de fondo le dio un toque celestial al bautizo de nuestra niña."',
    synopsis: 'Música sacra y coral diseñada para ceremonias religiosas y momentos sagrados.',
    soundtrackStyle: 'Música Sacra',
    emotionalTone: 'Sagrado y Divino',
    tags: ['Iglesia', 'Bautizo', 'Celestial'],
    viewsCount: 2200,
    likesCount: 350,
    lyricsSnippet: 'Luz divina que bajas del cielo para bendecir esta nueva alma...'
  },
  {
    id: 'cancion-infantil',
    title: '🧸 Infantil: Dulces Sueños',
    serviceType: 'cancion',
    category: 'bautizos',
    categoryLabel: 'Bautizos 🕊️',
    categoryIcon: '🕊️',
    audioUrl: '/audio/samples/infantil.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=1200',
    duration: '02:10',
    protagonists: 'Nacimiento de Mateo',
    clientQuote: '"Es la canción con la que lo arrullamos todas las noches. Simplemente mágica."',
    synopsis: 'Una tierna nana con xilófono y guitarra acústica para los más pequeños del hogar.',
    soundtrackStyle: 'Nana Infantil',
    emotionalTone: 'Tierno e Inocente',
    tags: ['Infantil', 'Nana', 'Bebés'],
    viewsCount: 3900,
    likesCount: 520,
    lyricsSnippet: 'Cierra tus ojitos, pequeño Mateo, que la luna ya bajó a cantar...'
  },
  {
    id: 'cancion-jazz',
    title: '🎷 Jazz: Noche Sofisticada',
    serviceType: 'cancion',
    category: 'celebraciones',
    categoryLabel: 'Celebraciones 🎉',
    categoryIcon: '🎉',
    audioUrl: '/audio/samples/jazz.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1415201364774-f6b0bb8019b8?q=80&w=1200',
    duration: '03:40',
    protagonists: 'Evento Corporativo',
    clientQuote: '"Elevó el prestigio de nuestra cena de gala. Un jazz impecable contando la historia de la empresa."',
    synopsis: 'Contrabajo, saxofón y una voz de terciopelo para un homenaje elegante y nocturno.',
    soundtrackStyle: 'Jazz Clásico',
    emotionalTone: 'Elegante y Sofisticado',
    tags: ['Jazz', 'Gala', 'Elegancia'],
    viewsCount: 1800,
    likesCount: 290,
    lyricsSnippet: 'En la brisa de la noche, el saxofón susurra nuestro éxito...'
  },
  {
    id: 'cancion-regueton',
    title: '🕺 Reguetón: Flow Urbano',
    serviceType: 'cancion',
    category: 'celebraciones',
    categoryLabel: 'Celebraciones 🎉',
    categoryIcon: '🎉',
    audioUrl: '/audio/samples/regueton.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1545128485-c400e7702796?q=80&w=1200',
    duration: '02:55',
    protagonists: 'Graduación Promo 2026',
    clientQuote: '"¡El beat estaba durísimo! La pusimos en el antro y todo el mundo la coreó."',
    synopsis: 'Ritmo urbano moderno, bajos fuertes y letras con mucho flow para celebrar sin parar.',
    soundtrackStyle: 'Urbano / Reguetón',
    emotionalTone: 'Dinámico y Urbano',
    tags: ['Reguetón', 'Fiesta', 'Urbano'],
    viewsCount: 7200,
    likesCount: 1400,
    lyricsSnippet: 'Ya salimos del colegio, ahora el mundo es nuestro, dale con todo el flow...'
  },
  {
    id: 'cancion-tango',
    title: '💃 Tango: Pasión Porteña',
    serviceType: 'cancion',
    category: 'celebraciones',
    categoryLabel: 'Celebraciones 🎉',
    categoryIcon: '🎉',
    audioUrl: '/audio/samples/tango.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544273574-d4fcc8c0e29b?q=80&w=1200',
    duration: '03:37',
    protagonists: 'Carlos & María',
    clientQuote: '"Bailamos esta canción en nuestro aniversario. La calidad del bandoneón es espectacular."',
    synopsis: 'Una celebración de 20 años de matrimonio musicalizada al puro estilo del tango tradicional porteño.',
    soundtrackStyle: 'Tango Clásico',
    emotionalTone: 'Pasional y Dramático',
    tags: ['Tango', 'Aniversario', 'Amor'],
    viewsCount: 1420,
    likesCount: 380,
    lyricsSnippet: 'La noche se queda en silencio, la luna se asoma al balcón...'
  },
  {
    id: 'cancion-opera',
    title: '🎭 Ópera: Drama Lírico',
    serviceType: 'cancion',
    category: 'homenajes',
    categoryLabel: 'Homenajes 🕊️',
    categoryIcon: '🕊️',
    audioUrl: '/audio/samples/opera.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507676184212-d0330a151b14?q=80&w=1200',
    duration: '03:50',
    protagonists: 'Homenaje a la Nonna',
    clientQuote: '"La voz de la soprano erizó la piel de los 100 invitados. Un trabajo maestro."',
    synopsis: 'Aria operística en italiano clásico, exaltando la memoria de la matriarca de la familia.',
    soundtrackStyle: 'Ópera Clásica',
    emotionalTone: 'Imponente y Sublime',
    tags: ['Ópera', 'Homenaje', 'Clásico'],
    viewsCount: 1100,
    likesCount: 200,
    lyricsSnippet: 'O dolce nonna, la tua voce è la nostra guida eterna...'
  }
];
